export const FETCH_SPECIMENS = "FETCH_SPECIMENS";
export const FETCH_SPECIMENS_BEGIN = "FETCH_SPECIMENS_BEGIN";
export const FETCH_SPECIMENS_SUCCESS = "FETCH_SPECIMENS_SUCCESS";
export const FETCH_SPECIMENS_FAILURE = "FETCH_SPECIMENS_FAILURE";
