export default {
  FETCH_SPECIMENS: "FETCH_SPECIMENS",
  FETCH_SPECIMENS_BEGIN: "FETCH_SPECIMENS_BEGIN",
  FETCH_SPECIMENS_SUCCESS: "FETCH_SPECIMENS_SUCCESS",
  FETCH_SPECIMENS_FAILURE: "FETCH_SPECIMENS_FAILURE",
  WORKSPACE_ADD_SPECIMEN: "WORKSPACE_ADD_SPECIMEN",
  SHOW_SPECIMENS: "SHOW_SPECIMENS"
};
